BEGIN;

TRUNCATE
  "prompts";

INSERT INTO "prompts" ("prompt")
VALUES
  ('scissors'),
  ('point'),
  ('tree'),
  ('airplane'),
  ('stairs'),
  ('string'),
  ('fetch'),
  ('cage'),
  ('mailbox'),
  ('spiderman'),
  ('puppet'),
  ('penguin'),
  ('shovel'),
  ('popcorn'),
  ('butter'),
  ('trumpet'),
  ('owl'),
  ('honk'),
  ('chalk'),
  ('story'),
  ('oar'),
  ('throne'),
  ('gingerbread'),
  ('lawnmower'),
  ('carpenter'),
  ('shrink'),
  ('tachometer'),
  ('olive oil'),
  ('boundary'),
  ('all bark and no bite'),
  ('a chip on your shoulder'),
  ('water under the bridge'),
  ('make a mountain out of a mole-hill'),
  ('pull the wool over your eyes'),
  ('fingerlickin good'),
  ('method to my madness'),
  ('crane'),
  ('shark'),
  ('donkey'),
  ('dolphin'),
  ('monkey'),
  ('michael jordan'),
  ('batman'),
  ('benjamin franklin'),
  ('CHUCK NORRIS'),
  ('john lennon'),
  ('charlie brown'),
  ('clark kent'),
  ('101 dalmations'),
  ('beauty and the beast'),
  ('good will hunting'),
  ('the truman show'),
  ('aladdin'),
  ('full metal jacket'),
  ('the terminator'),
  ('harry potter'),
  ('mythbusters'),
  ('how i met your mother'),
  ('rugrats'),
  ('e-r'),
  ('coil'),
  ('goldfish'),
  ('frankenstein'),
  ('peck'),
  ('windmill'),
  ('bobsled'),
  ('sand'),
  ('year'),
  ('stain'),
  ('vest'),
  ('swordfish'),
  ('pizza'),
  ('softball'),
  ('party'),
  ('wrench'),
  ('hair'),
  ('spine'),
  ('beetle'),
  ('trip'),
  ('gym'),
  ('sip'),
  ('torch'),
  ('cowboy'),
  ('carrot'),
  ('beggar'),
  ('lung'),
  ('basket'),
  ('flamingo'),
  ('cuff'),
  ('dryer');

COMMIT;

  